### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by robertcatgithub** [1xch/flask-celery-example#3]
Suggest that you indicate that you're using Redis

**Comment by 1xch** [comment]
Where would you suggest making this note -- perhaps fork, edit, and submit a pull request for review.

**Comment by wadewilliams** [comment]
Since [this is identical to the flask documentation](http://flask.pocoo.org/docs/0.10/patterns/celery/#minimal-example) I would say close this issue. It would be nice if there wasn't additional configuration needed in order to run this right out of the gate, but you're consistent with the documentation here.
